FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

#install npm
RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get -y install nodejs
RUN node -v
RUN npm -v

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["TerraformTest/TerraformTest.csproj", "TerraformTest/"]
RUN dotnet restore "TerraformTest/TerraformTest.csproj"
COPY . .
WORKDIR "/src/TerraformTest"
RUN dotnet build "TerraformTest.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TerraformTest.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TerraformTest.dll"]