version: 0.2

env:
  variables:
    testy: "hello world"

phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y jq
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install -g npm@latest
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: 'TerraformTest/staging'
